# Generated by Django 4.0.4 on 2022-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.IntegerField(default=12132),
            preserve_default=False,
        ),
    ]
